// Deliberately narrow same-system bridge. The workspace may invoke the audited
// fresh Browser Worker client and derive its read-only display projection, but
// it cannot import the adapter host UI or the upstream iztro package directly.
export {
  ZIWEI_CORE_MINOR_STAR_SANFANG_REVIEW_FEEDBACK_MAX_BYTES,
  ZIWEI_HIGH_RISK_FEEDBACK_DOM_COMMON_SOURCE_FIELDS,
  ZIWEI_HIGH_RISK_FEEDBACK_DOM_DECISION_MAP_VERSION,
  ZIWEI_HIGH_RISK_FEEDBACK_DOM_EXCLUDED_CATEGORIES,
  ZIWEI_HIGH_RISK_FEEDBACK_DOM_SURFACE_IDS,
  ZIWEI_HIGH_RISK_FEEDBACK_DOM_TEXT_ROLE,
  ZIWEI_CORE_MINOR_STAR_SANFANG_REVIEW_FEEDBACK_PROFILE,
  ZIWEI_NATAL_TRANSFORMATION_PALACE_REVIEW_FEEDBACK_FILENAME,
  ZIWEI_NATAL_TRANSFORMATION_PALACE_REVIEW_FEEDBACK_MAX_BYTES,
  calculateZiweiInFreshBrowserWorker,
  createZiweiCoreMinorStarSanfangFeedbackDomDecisionView,
  createZiweiBrowserDisplayProjection,
  createZiweiHighRiskFeedbackDomDecisionKey,
  createZiweiHighRiskEgressDecisionKey,
  createZiweiHighRiskEgressDecisionMap,
  createZiweiCoreMinorStarSanfangReviewFeedbackTemplate,
  createZiweiNatalTransformationPalaceReviewFeedbackTemplate,
  createZiweiNatalTransformationPalaceFeedbackDomDecisionView,
  getZiweiCoreMinorStarSanfangFeedbackDomDecisionEntry,
  getZiweiHighRiskEgressDecisionEntry,
  getZiweiNatalTransformationPalaceFeedbackDomDecisionEntry,
  isZiweiCoreMinorStarSanfangFeedbackDomDecisionMap,
  isZiweiHighRiskEgressDecisionMap,
  isZiweiNatalTransformationPalaceFeedbackDomDecisionMap,
  preflightZiweiCoreMinorStarSanfangReviewFeedback,
  preflightZiweiNatalTransformationPalaceReviewFeedback,
  serializeZiweiCoreMinorStarSanfangReviewFeedbackTemplate,
  serializeZiweiNatalTransformationPalaceReviewFeedbackTemplate,
  ziweiCoreMinorStarSanfangReviewFeedbackFilename
} from "../../ziwei-iztro-adapter-draft/src/browser-preview/browser-client.ts";

export type {
  BrowserProbeDisplayProjection,
  BrowserProbeSuccessResult,
  ZiweiCoreMinorStarSanfangFeedbackDomDecisionView,
  ZiweiHighRiskFeedbackDomDecisionEntry,
  ZiweiHighRiskFeedbackDomDecisionMap,
  ZiweiHighRiskFeedbackDomSourceField,
  ZiweiHighRiskFeedbackDomSurfaceId,
  ZiweiHighRiskEgressDecisionEntry,
  ZiweiHighRiskEgressDecisionMap,
  ZiweiHighRiskEgressIncludedTextRole,
  ZiweiHighRiskEgressSourceSurfaceId,
  ZiweiBrowserCalculationOptions,
  ZiweiCoreMinorStarSanfangReviewFeedbackEnvelope,
  ZiweiCoreMinorStarSanfangReviewFeedbackItem,
  ZiweiCoreMinorStarSanfangReviewFeedbackPreflight,
  ZiweiNatalTransformationPalaceReviewFeedbackEnvelope,
  ZiweiNatalTransformationPalaceFeedbackDomDecisionView,
  ZiweiNatalTransformationPalaceReviewFeedbackPreflight,
  ZiweiNatalTransformationPalaceReviewItem
} from "../../ziwei-iztro-adapter-draft/src/browser-preview/browser-client.ts";
